import { Tray, Menu, nativeImage } from 'electron'
import trayIdle from '../../resources/tray/tray-idle.png?asset'
import trayTalking from '../../resources/tray/tray-talking.png?asset'
import trayMuted from '../../resources/tray/tray-muted.png?asset'
import trayDeafened from '../../resources/tray/tray-deafened.png?asset'

// Windows system-tray presence with a live mic indicator (like TeamSpeak). The
// renderer pushes a single voice-state string over IPC; we swap the icon +
// tooltip. Icons are generated by scripts/gen-tray-icons.mjs.
const ICON_PATHS = {
  idle: trayIdle,
  talking: trayTalking,
  muted: trayMuted,
  deafened: trayDeafened
}
const TOOLTIPS = {
  idle: 'Pylon — mic active',
  talking: 'Pylon — talking',
  muted: 'Pylon — mic muted',
  deafened: 'Pylon — deafened'
}

let tray = null
let images = {}
let getWindow = () => null
let quitApp = () => {}
let currentState = null

function showWindow() {
  const win = getWindow()
  if (!win) return
  if (win.isMinimized()) win.restore()
  win.show()
  win.focus()
}

// The menu's Mute/Deafen ride the same keybinds:trigger channel the global
// shortcuts and in-app buttons use, so all three stay in sync (see SideBar).
function trigger(action) {
  getWindow()?.webContents.send('keybinds:trigger', action)
}

// win32 only — the tray + close-to-tray behaviour is scoped to Windows for now.
export function setupTray({ getWindow: windowGetter, quit }) {
  if (process.platform !== 'win32' || tray) return
  getWindow = windowGetter
  quitApp = quit

  images = Object.fromEntries(
    Object.entries(ICON_PATHS).map(([state, path]) => [state, nativeImage.createFromPath(path)])
  )

  tray = new Tray(images.idle)
  tray.setToolTip(TOOLTIPS.idle)
  tray.setContextMenu(
    Menu.buildFromTemplate([
      { label: 'Open Pylon', click: showWindow },
      { type: 'separator' },
      { label: 'Toggle Mute', click: () => trigger('toggleMicMute') },
      { label: 'Toggle Deafen', click: () => trigger('toggleSoundMute') },
      { type: 'separator' },
      { label: 'Quit Pylon', click: () => quitApp() }
    ])
  )
  tray.on('click', showWindow)
  tray.on('double-click', showWindow)
  currentState = 'idle'
}

export function setTrayVoiceState(state) {
  if (!tray || state === currentState || !images[state]) return
  currentState = state
  tray.setImage(images[state])
  tray.setToolTip(TOOLTIPS[state])
}

export function destroyTray() {
  tray?.destroy()
  tray = null
  currentState = null
}
