/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A running capture. Frames arrive on `on_frame` as Buffers of FRAME_BYTES
 * (10ms interleaved f32le stereo @ 48kHz), called from a capture thread via
 * a threadsafe function. Fatal capture errors arrive on `on_error`, after
 * which no more frames are delivered.
 */
export declare class CaptureSession {
  get backend(): string
  stop(): void
}

export interface AudioApp {
  /** Backend-specific capture target: Windows = PID, Linux = PipeWire node id */
  id: string
  name: string
  pid?: number
  binary?: string
}

export declare function capabilities(): Capabilities

export interface Capabilities {
  /** Which capture backend is active: 'wasapi-process-loopback' | 'pipewire' | 'none' */
  backend: string
  /** Can capture a single application's audio (by PID on Windows, node on Linux) */
  perApp: boolean
  /** Can capture system audio while excluding this app's own process tree */
  excludeSelf: boolean
  /** Can capture plain system-wide audio through this addon */
  system: boolean
  /** When backend is 'none': why the capability probe failed */
  reason?: string
}

export interface CaptureOptions {
  /** 'stub' | 'app' | 'system' | 'system-exclude-self' */
  mode: string
  /** Capture targets for 'app' mode (AudioApp.id values) */
  targets?: Array<string>
}

export declare function listApps(): Array<AudioApp>

export declare function startCapture(options: CaptureOptions, onFrame: ((err: Error | null, arg: Buffer) => any), onError: ((err: Error | null, arg: string) => any)): CaptureSession
